# Generated by Django 4.1.3 on 2022-11-28 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_vagas_empresa'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.vagas'),
        ),
    ]
